USE `autobasedb`;

INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('1', '53', 'Technical Assistance', '53', '1', '54.64');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('2', '97', 'Implementation', '97', '1', '51.71');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('3', '61', 'On-site Service', '61', '3', '94.28');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('4', '88', 'System Configuration', '88', '1', '48.19');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('5', '91', 'Monitoring', '91', '2', '58.54');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('6', '8', 'Integration', '8', '2', '63.58');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('7', '23', 'Support', '23', '1', '53.22');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('8', '71', 'Upgrade', '71', '1', '53.54');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('9', '98', 'Installation', '98', '3', '107.74');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('10', '17', 'Project Management', '17', '3', '124.22');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('11', '32', 'Design', '32', '2', '72.02');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('12', '48', 'Data Migration', '48', '1', '23.88');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('13', '93', 'Repair', '93', '1', '42.81');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('14', '20', 'Customization', '20', '2', '60.02');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('15', '95', 'Inspection', '95', '1', '41.79');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('16', '52', 'Consulting', '52', '2', '92.36');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('17', '45', 'Maintenance', '45', '1', '27.40');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('18', '36', 'Remote Assistance', '36', '1', '49.75');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('19', '39', 'Troubleshooting', '39', '1', '38.71');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('20', '56', 'Training', '56', '4', '137.97');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('21', '24', 'Design', '24', '2', '72.96');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('22', '77', 'Integration', '77', '2', '81.46');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('23', '64', 'Training', '64', '2', '87.18');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('24', '43', 'Implementation', '43', '2', '81.64');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('25', '46', 'Remote Assistance', '46', '2', '63.43');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('26', '28', 'Repair', '28', '2', '82.79');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('27', '44', 'On-site Service', '44', '2', '62.01');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('28', '22', 'Inspection', '22', '1', '52.86');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('29', '33', 'Installation', '33', '2', '93.23');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('30', '31', 'Monitoring', '31', '1', '49.90');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('31', '15', 'Data Migration', '15', '1', '45.26');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('32', '50', 'Support', '50', '2', '56.42');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('33', '86', 'Upgrade', '86', '2', '90.67');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('34', '70', 'Troubleshooting', '70', '2', '78.47');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('35', '29', 'Project Management', '29', '0', '16.59');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('36', '59', 'Customization', '59', '3', '95.42');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('37', '1', 'System Configuration', '1', '3', '123.88');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('38', '41', 'Consulting', '41', '2', '78.61');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('39', '69', 'Technical Assistance', '69', '3', '97.51');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('40', '67', 'Maintenance', '67', '2', '68.84');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('41', '75', 'Consulting', '75', '2', '89.30');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('42', '57', 'Troubleshooting', '57', '3', '95.18');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('43', '65', 'Project Management', '65', '2', '92.26');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('44', '7', 'Design', '7', '2', '91.46');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('45', '18', 'Training', '18', '3', '109.09');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('46', '85', 'Inspection', '85', '0', '16.13');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('47', '14', 'Support', '14', '1', '41.05');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('48', '68', 'Technical Assistance', '68', '1', '49.70');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('49', '47', 'Maintenance', '47', '2', '88.17');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('50', '79', 'On-site Service', '79', '4', '146.34');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('51', '83', 'Remote Assistance', '83', '3', '95.71');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('52', '63', 'Integration', '63', '1', '49.46');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('53', '60', 'Installation', '60', '3', '113.64');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('54', '96', 'Customization', '96', '3', '110.49');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('55', '94', 'Data Migration', '94', '2', '70.46');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('56', '76', 'Implementation', '76', '2', '78.70');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('57', '38', 'Monitoring', '38', '2', '62.44');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('58', '73', 'Repair', '73', '3', '101.04');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('59', '66', 'System Configuration', '66', '2', '66.41');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('60', '21', 'Upgrade', '21', '3', '95.37');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('61', '42', 'Monitoring', '42', '3', '116.32');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('62', '80', 'Integration', '80', '1', '45.33');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('63', '25', 'Repair', '25', '3', '107.65');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('64', '54', 'On-site Service', '54', '3', '112.24');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('65', '26', 'Design', '26', '2', '79.41');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('66', '62', 'Data Migration', '62', '3', '103.30');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('67', '34', 'Inspection', '34', '2', '88.83');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('68', '58', 'Support', '58', '2', '65.12');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('69', '81', 'Troubleshooting', '81', '2', '62.88');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('70', '90', 'Maintenance', '90', '2', '69.81');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('71', '11', 'Customization', '11', '2', '79.44');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('72', '55', 'Training', '55', '3', '112.48');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('73', '100', 'Upgrade', '100', '2', '74.89');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('74', '2', 'Consulting', '2', '1', '48.78');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('75', '5', 'Implementation', '5', '1', '49.09');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('76', '10', 'Remote Assistance', '10', '3', '107.54');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('77', '37', 'Installation', '37', '2', '67.82');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('78', '19', 'System Configuration', '19', '2', '68.75');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('79', '16', 'Technical Assistance', '16', '2', '76.79');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('80', '9', 'Project Management', '9', '2', '78.71');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('81', '3', 'Project Management', '3', '1', '45.50');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('82', '27', 'Data Migration', '27', '3', '111.18');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('83', '74', 'Training', '74', '1', '55.27');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('84', '13', 'Repair', '13', '1', '31.97');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('85', '92', 'Customization', '92', '2', '68.52');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('86', '99', 'Consulting', '99', '2', '87.90');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('87', '12', 'Upgrade', '12', '2', '93.34');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('88', '40', 'Maintenance', '40', '3', '112.29');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('89', '30', 'Design', '30', '2', '86.03');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('90', '78', 'Monitoring', '78', '2', '64.75');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('91', '89', 'Remote Assistance', '89', '2', '81.78');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('92', '84', 'Support', '84', '2', '93.44');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('93', '72', 'Technical Assistance', '72', '1', '48.43');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('94', '4', 'Troubleshooting', '4', '2', '84.22');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('95', '35', 'Implementation', '35', '3', '96.35');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('96', '87', 'System Configuration', '87', '1', '49.43');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('97', '51', 'Inspection', '51', '2', '68.35');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('98', '49', 'Installation', '49', '2', '71.49');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('99', '82', 'On-site Service', '82', '1', '55.39');
INSERT INTO `ServiceLine` (ServiceLineID, ServiceOrderID, ServiceType, PartID, LaborHours, LaborRate) VALUES ('100', '6', 'Integration', '6', '2', '74.66');