USE `autobasedb`;

INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('1', 'Spinach and Cheese Quiche', '5.49', '73');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('2', 'Fleece Hoodie', '39.99', '69');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('3', 'Raspberry Tart', '5.49', '126');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('4', 'Peach Salsa', '3.29', '64');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('5', 'Organic Granola', '5.49', '78');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('6', 'Herb Seasoned Croutons', '2.99', '85');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('7', 'Silicone Ice Cube Tray', '10.99', '71');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('8', 'Hummus Trio Pack', '5.49', '71');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('9', 'Roasted Garlic Mashed Potatoes', '3.99', '144');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('10', 'Foldable Picnic Table', '49.99', '166');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('11', 'Set of Silicone Baking Molds', '15.99', '96');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('12', 'Cocoa Powder', '3.99', '32');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('13', 'Tattoo Kit', '99.99', '57');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('14', 'Adjustable Height Standing Desk Converter', '89.99', '80');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('15', 'Rolling Cooler', '59.99', '56');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('16', 'Compact Umbrella', '12.99', '123');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('17', 'Compact Pop-Up Tent', '69.99', '37');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('18', 'Chipotle Sauce', '3.29', '66');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('19', 'Caribbean Jerk Marinade', '3.79', '52');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('20', 'Bamboo Cutting Board Set', '34.99', '184');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('21', 'Pet Hair Vacuum Attachment', '14.99', '97');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('22', 'Classic Cheesecake Mix', '4.99', '109');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('23', 'Durable Hiking Boots', '89.99', '116');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('24', 'Manual Coffee Grinder', '22.99', '109');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('25', 'Creamy Ranch Dressing', '2.49', '85');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('26', 'Spinach Feta Wraps', '4.29', '110');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('27', 'Folding Pocket Knife', '24.99', '83');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('28', 'Chicken Parmesan Dinner Kit', '14.99', '70');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('29', 'Apple Cinnamon Instant Oatmeal', '3.49', '124');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('30', 'Ice Cream Scoop', '12.99', '67');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('31', 'Mushroom Soup (canned)', '2.49', '60');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('32', 'Herb Seasoned Couscous', '2.49', '75');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('33', 'Insulated Coffee Mug', '24.99', '121');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('34', 'Infrared Thermometer Gun', '29.99', '105');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('35', 'Artisan Pickles', '2.49', '22');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('36', 'Granola Cereal', '4.49', '127');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('37', 'Measuring Cups Set', '19.99', '165');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('38', 'Stuffed Bell Peppers', '5.99', '105');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('39', 'Wrap Front Midi Skirt', '44.99', '130');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('40', 'Buffalo Cauliflower Wings', '6.99', '92');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('41', 'Fitness Activity Journal', '14.99', '119');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('42', 'Lentil Pasta', '4.99', '127');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('43', 'Truffle Parmesan Fries', '4.99', '123');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('44', 'Backpack', '49.99', '122');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('45', 'Dish Rack', '24.99', '145');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('46', 'Wall Art', '45', '22');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('47', 'Canned Coconut Milk', '1.89', '55');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('48', 'LED Desk Lamp with USB Charging Port', '29.99', '66');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('49', 'Children''s Garden Tool Set', '22.99', '118');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('50', 'Pet Water Fountain with Filtration', '39.99', '195');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('51', 'Ergonomic Gaming Chair', '199.99', '128');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('52', 'Cable Knit Cardigan', '49.99', '66');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('53', 'Stuffed Peppers with Quinoa', '7.99', '152');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('54', 'LED Canopy Lights', '29.99', '147');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('55', 'Samsung Galaxy Smartwatch', '249.99', '94');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('56', 'Pumpkin Ice Cream', '4.99', '105');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('57', 'Microwave Popcorn Maker', '19.99', '83');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('58', 'Ginger Turmeric Latte Mix', '5.29', '135');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('59', 'Digital Kitchen Timer', '14.99', '89');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('60', 'Cabbage', '1.29', '127');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('61', 'Wrap Jumpsuit', '54.99', '155');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('62', 'Portable Massage Gun', '79.99', '60');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('63', 'Magnetic Spice Containers', '24.99', '144');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('64', 'Vegan chocolate chip cookies', '4.79', '150');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('65', 'Asian Stir-Fry Vegetables', '2.99', '106');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('66', 'Fruit Infuser Water Bottle', '15.99', '138');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('67', 'Fresh Strawberries', '3.99', '118');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('68', 'Air Mattress', '49.99', '87');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('69', 'Jasmine Rice', '2.39', '84');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('70', 'Magnet Travel Fridge Magnets', '12.99', '93');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('71', 'Vegetable Potstickers', '5.99', '106');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('72', 'Trackpad for Laptop', '49.99', '150');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('73', 'Strawberry Banana Smoothie Pack', '4.99', '100');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('74', 'LED Strip Light Kit', '39.99', '65');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('75', 'Saffron Rice Mix', '2.99', '65');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('76', 'Classic Caesar Dressing', '3.49', '143');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('77', 'Electric Butter Churn', '49.99', '90');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('78', 'Elegant Lace Dress', '79.99', '92');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('79', 'Savory Breakfast Sausage', '6.49', '102');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('80', 'Chickpea Pasta', '4.19', '105');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('81', 'Nutty Quinoa Salad', '4.99', '61');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('82', 'Classic Watch', '99.99', '148');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('83', 'Window Blinds', '59.99', '74');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('84', 'Automatic Pet Feeder', '69.99', '43');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('85', 'Bodyweight Resistance Bands', '22.99', '91');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('86', 'Almond Joy Munch Bars', '1.39', '117');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('87', 'Coconut Milk Yogurt', '2.99', '124');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('88', 'Non-Toxic Concrete Sealer', '39.99', '150');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('89', 'Sweet Potato Noodles', '3.79', '115');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('90', 'Portable Ice Maker', '199.99', '86');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('91', 'Safety First Aid Kit', '29.99', '109');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('92', 'High-Quality Yoga Mat', '34.99', '125');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('93', 'Fashionable Belt Bag', '34.99', '65');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('94', 'Plant Growing Kit', '22.99', '112');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('95', 'Italian Sausage Links', '5.99', '128');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('96', 'Bamboo Memory Foam Pillow', '34.99', '66');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('97', 'Coffee Capsule Dispenser', '24.99', '91');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('98', 'Ramen Noodles', '0.99', '95');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('99', 'Pet Hair Removal Brush', '14.99', '74');
INSERT INTO `Part` (PartID, PartName, Price, Stock) VALUES ('100', 'Almond Joy Protein Bars', '1.99', '100');