USE `autobasedb`;

INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('1', 'Technical Support', '5', '47.44');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('2', 'Software Development', '10', '93.32');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('3', 'Audit', '5', '51.07');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('4', 'Installation', '4', '33.48');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('5', 'Integration', '9', '79.97');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('6', 'Data Migration', '8', '71.94');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('7', 'Consulting', '5', '43.26');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('8', 'Network Configuration', '8', '77.57');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('9', 'Remote Assistance', '9', '86.90');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('10', 'Maintenance', '7', '65.89');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('11', 'Project Management', '6', '56.39');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('12', 'Troubleshooting', '9', '88.99');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('13', 'System Monitoring', '10', '97.78');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('14', 'Training', '9', '83.82');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('15', 'Implementation', '12', '108.86');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('16', 'On-site Service', '6', '58.35');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('17', 'Upgrade', '9', '79.69');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('18', 'Inspection', '11', '106.16');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('19', 'Repair', '11', '107.45');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('20', 'Customization', '11', '98.56');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('21', 'Data Migration', '11', '106.13');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('22', 'Repair', '7', '62.61');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('23', 'Installation', '6', '58.34');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('24', 'Troubleshooting', '10', '97.82');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('25', 'Inspection', '6', '56.83');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('26', 'Integration', '13', '117.52');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('27', 'Software Development', '10', '91.68');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('28', 'Customization', '6', '59.56');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('29', 'Audit', '7', '65.86');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('30', 'Implementation', '11', '106.32');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('31', 'Maintenance', '8', '77.86');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('32', 'System Monitoring', '11', '106.15');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('33', 'Consulting', '10', '97.87');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('34', 'Remote Assistance', '7', '62.28');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('35', 'Network Configuration', '11', '103.71');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('36', 'Technical Support', '8', '79.50');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('37', 'Training', '5', '49.46');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('38', 'Project Management', '8', '70.53');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('39', 'On-site Service', '8', '75.00');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('40', 'Upgrade', '9', '82.67');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('41', 'Training', '6', '52.12');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('42', 'Network Configuration', '8', '75.27');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('43', 'Repair', '5', '49.98');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('44', 'Maintenance', '5', '45.00');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('45', 'Troubleshooting', '4', '39.60');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('46', 'Software Development', '13', '120.44');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('47', 'Audit', '5', '48.43');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('48', 'Technical Support', '9', '87.94');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('49', 'On-site Service', '9', '88.25');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('50', 'Remote Assistance', '4', '42.21');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('51', 'Integration', '8', '75.25');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('52', 'Upgrade', '11', '99.72');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('53', 'Inspection', '12', '113.11');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('54', 'Customization', '6', '58.95');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('55', 'Project Management', '7', '69.39');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('56', 'System Monitoring', '9', '87.31');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('57', 'Consulting', '4', '42.01');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('58', 'Implementation', '10', '97.73');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('59', 'Installation', '6', '55.66');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('60', 'Data Migration', '10', '89.74');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('61', 'On-site Service', '7', '65.42');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('62', 'Repair', '7', '69.26');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('63', 'Project Management', '9', '88.47');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('64', 'Software Development', '4', '35.76');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('65', 'Training', '11', '100.23');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('66', 'Network Configuration', '6', '54.84');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('67', 'Customization', '8', '70.50');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('68', 'Maintenance', '9', '82.02');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('69', 'Installation', '7', '66.44');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('70', 'Technical Support', '11', '106.83');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('71', 'Integration', '6', '60.73');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('72', 'Consulting', '5', '45.99');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('73', 'Upgrade', '6', '59.47');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('74', 'Troubleshooting', '11', '102.46');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('75', 'Data Migration', '12', '108.59');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('76', 'Remote Assistance', '11', '103.66');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('77', 'System Monitoring', '11', '102.99');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('78', 'Implementation', '12', '110.34');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('79', 'Inspection', '8', '79.68');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('80', 'Audit', '10', '90.76');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('81', 'Upgrade', '10', '97.21');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('82', 'Project Management', '9', '83.51');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('83', 'Data Migration', '7', '64.05');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('84', 'Implementation', '8', '71.59');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('85', 'Troubleshooting', '10', '89.51');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('86', 'Training', '9', '82.62');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('87', 'Installation', '10', '91.30');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('88', 'On-site Service', '7', '68.23');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('89', 'Maintenance', '7', '62.84');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('90', 'Integration', '8', '70.39');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('91', 'Repair', '4', '39.29');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('92', 'Software Development', '6', '59.20');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('93', 'Customization', '11', '106.69');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('94', 'Remote Assistance', '8', '71.93');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('95', 'Technical Support', '10', '90.30');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('96', 'Inspection', '10', '92.69');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('97', 'System Monitoring', '5', '44.64');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('98', 'Consulting', '9', '81.84');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('99', 'Network Configuration', '8', '73.54');
INSERT INTO `ServiceLine` (ID, Service_Type, Labor_Hours, Labor_Rate) VALUES ('100', 'Audit', '10', '97.23');