USE `autobasedb`;

INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('1', 'Vanilla Pudding Mix', '1.29', '187');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('2', 'Lentil Pasta', '4.99', '88');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('3', 'Self-Cleaning Cat Litter Box', '199.99', '68');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('4', 'Summer Tank Dress', '39.99', '79');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('5', 'Spinach and Feta Wraps', '4.99', '98');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('6', 'Frozen Mixed Vegetables', '1.99', '25');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('7', 'Multifunctional Baby Bottle Warmer', '39.99', '98');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('8', 'Graphic Sweatshirt', '34.99', '113');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('9', 'Educational STEM Kit', '35.99', '124');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('10', 'Knitted Infinity Scarf', '29.99', '129');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('11', 'Organic Coconut Yogurt', '4.49', '84');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('12', 'Cotton Basic Tank', '14.99', '99');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('13', 'Sketchbook', '14.99', '65');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('14', 'Foot Massager Machine', '59.99', '83');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('15', 'Adjustable Laptop Desk', '59.99', '126');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('16', 'Winter Insulated Jacket', '89.99', '97');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('17', 'Thai Green Curry Paste', '2.49', '106');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('18', 'Fitness Jump Rope', '15.99', '76');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('19', 'Dog Walking Waist Pack', '19.99', '105');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('20', 'Kale and Quinoa Salad', '6.49', '125');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('21', 'Garlic Herb Grilled Chicken', '8.99', '102');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('22', 'Organic Coconut Flour', '5.49', '130');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('23', 'Leather Crossbody Bag', '89.99', '129');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('24', 'Cocktail Shaker and Mixing Glass Set', '39.99', '142');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('25', 'Teriyaki Chicken Skewers', '8.99', '157');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('26', 'Fire Roasted Salsa', '2.49', '108');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('27', 'Organic Coconut Oil', '8.99', '115');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('28', 'Kids Tablet', '129.99', '93');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('29', 'Shoe Organizer', '39.99', '136');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('30', 'Tailgating Set', '89.99', '118');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('31', 'Snack Container Set', '19.99', '83');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('32', 'Sea Salt Tortilla Chips', '2.49', '67');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('33', 'Foam Roller for Muscle Recovery', '29.99', '157');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('34', 'Outdoor Adventure Backpack', '59.99', '84');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('35', 'Cereal Dispenser with Portion Control', '24.99', '72');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('36', 'Digital Camera', '299.99', '130');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('37', 'Pet Grooming Glove', '12.99', '120');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('38', '3D Night Light', '19.99', '75');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('39', 'Organic Brown Rice Cakes', '3.99', '151');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('40', 'Spinach and Ricotta Ravioli', '6.49', '62');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('41', 'LED Desk Lamp with USB Charging', '39.99', '165');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('42', 'Portable Massage Gun', '79.99', '152');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('43', 'Handmade Soap Making Kit', '34.99', '102');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('44', 'Weighted Jump Rope with Counter', '14.99', '143');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('45', 'Mini Fondue Set', '34.99', '74');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('46', 'Coffee Making Kit', '44.99', '113');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('47', 'Compact Portable Grill', '79.99', '153');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('48', 'Herbal Tea Sampler Box', '29.99', '92');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('49', 'Frozen Edamame', '3.29', '46');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('50', 'Tea Infuser', '12.99', '84');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('51', 'Chicken Fajita Kit', '8.99', '67');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('52', 'Rechargeable Battery Organizer', '17.99', '108');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('53', 'Fruit and Nut Medley', '5.99', '70');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('54', 'Zucchini Noodles', '3.99', '96');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('55', 'Recipe Book Stand', '22.99', '76');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('56', 'Fresh Basil', '1.99', '48');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('57', 'Hiking Water Bottle with Filter', '29.99', '150');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('58', 'Emergency Preparedness Kit', '99.99', '138');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('59', 'Miso Dressing', '3.49', '60');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('60', 'Adjustable Window Blind', '49.99', '79');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('61', 'Electric Griddle with Lid', '49.99', '131');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('62', 'Chocolate Chip Energy Balls', '3.99', '106');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('63', 'Outdoor Inflatable Pool', '149.99', '117');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('64', 'Sliced Provolone Cheese', '3.99', '76');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('65', 'Adjustable Kitchen Broom Stand', '14.99', '114');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('66', 'Non-Stick Grill Mat', '19.99', '123');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('67', 'Pine Nuts', '7.99', '130');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('68', 'Interchangeable Watch Bands', '24.99', '100');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('69', 'Pumpkin Spice Latte Mix', '3.29', '106');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('70', 'Non-Slip Yoga Socks', '12.99', '142');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('71', 'Organic Whole Grain Oats', '2.49', '91');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('72', 'Vegetarian Chili', '3.99', '111');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('73', 'Travel Orthopedic Pillow', '24.99', '106');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('74', 'Leather Notebook Cover', '29.99', '126');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('75', 'Children''s Gardening Set', '19.99', '103');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('76', 'Pineapple Coconut Bars', '3.79', '48');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('77', 'Garden Tool Belt', '22.99', '75');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('78', 'Graphic Print Leggings', '29.99', '167');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('79', 'Artisan Pickles', '2.49', '85');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('80', 'Maple Cinnamon Almonds', '4.29', '117');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('81', 'Pineapple Rings', '2.49', '95');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('82', 'Savory Rice Cakes', '2.5', '53');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('83', 'Almond Joy Munch Bars', '1.39', '133');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('84', 'BBQ Lentil Chips', '3.49', '78');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('85', 'Chia Seed Pudding Mix', '4.19', '85');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('86', 'Green Smoothie Mix', '5.99', '69');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('87', 'Quinoa Salad', '5.99', '143');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('88', 'Coconut Cream Pie', '9.49', '133');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('89', 'Chocolate Mint Thins', '2.99', '79');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('90', 'Garlic and Herb Cream Cheese', '3.49', '66');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('91', 'Tahini', '5.49', '92');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('92', 'LED Camping Lantern with USB Charging', '34.99', '75');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('93', 'Gardening Kneeler and Seat', '39.99', '132');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('94', 'Insulated Wine Tote', '24.99', '143');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('95', 'Oatmeal Raisin Cookies', '3.49', '111');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('96', 'Arcade Game Machine', '299.99', '113');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('97', 'Window Blinds', '59.99', '83');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('98', 'Ripped Boyfriend Jeans', '54.99', '55');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('99', 'Almond Joy Protein Bars', '1.99', '85');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('100', 'Peanut Butter Cookies', '3.49', '77');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('101', 'Fitness Tracker', '49.99', '95');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('102', 'Wild Rice Pilaf', '3.79', '124');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('103', 'Pet Bed with Removable Cover', '49.99', '58');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('104', 'Spicy Vegetable Sushi Rolls', '8.49', '83');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('105', 'Vegan Protein Powder', '34.99', '110');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('106', 'Pineapple Coconut Rice Mix', '3.99', '89');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('107', 'Grapes (red)', '3.49', '95');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('108', 'Garden Hose', '32.99', '102');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('109', 'Solar Power Bank', '39.99', '46');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('110', 'Fresh Strawberries', '3.99', '97');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('111', 'Energy Bites', '3.99', '133');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('112', 'Portable Pet Bathing Tool', '29.99', '121');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('113', 'Pizza Stone', '29.99', '92');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('114', 'Mini Air Hockey Table', '39.99', '126');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('115', 'Outdoor String Lights', '24.99', '156');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('116', 'Scented Soy Candles', '19.99', '95');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('117', 'Wild Rice & Quinoa Mix', '2.99', '55');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('118', 'Wireless Earbud Silicone Covers', '9.99', '74');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('119', 'Dried Fruit Medley', '5.49', '79');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('120', 'Halloween Decoration Set', '29.99', '128');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('121', 'Caramel Apple Taffy', '1.99', '62');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('122', 'Portable Solar Camp Shower', '29.99', '121');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('123', 'Cinnamon Roll Dough', '4.49', '136');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('124', 'Chocolate Peanut Butter Cups', '2.29', '51');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('125', 'Vegan Chocolate Cake Mix', '4.29', '129');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('126', 'Pineapple Chunks (canned)', '2.29', '121');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('127', 'Smartphone Gimbal Stabilizer', '89.99', '60');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('128', 'Comfortable Jogger Pants', '29.99', '80');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('129', 'Smartphone Projector Kit', '24.99', '73');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('130', 'Marinara Parmesan Baked Ziti', '8.49', '118');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('131', 'Apple Juice', '3.29', '81');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('132', 'Yoga Mat Carrier', '12.99', '153');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('133', 'Tattoo Kit', '99.99', '59');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('134', 'Honey Mustard Dip', '3.29', '101');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('135', 'Spicy Garlic Edamame', '3.99', '82');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('136', 'Maple Cinnamon Granola Bars', '3.49', '130');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('137', 'Chino Shorts', '34.99', '76');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('138', 'Body Pillow Case', '14.99', '79');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('139', 'Coconut Cashew Yogurt', '1.99', '117');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('140', 'Garden Vegetable Chips', '3.49', '115');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('141', 'Organic Italian Seasoning', '2.99', '134');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('142', 'Pet Caress Brush', '12.99', '51');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('143', 'Balsamic Fig Dressing', '3.79', '106');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('144', 'Vegetable Fried Rice Mix', '3.99', '63');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('145', 'Portable Camping Stove', '49.99', '112');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('146', 'Protein Pancake Mix', '3.99', '157');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('147', 'Collapsible Pet Dog Bowl', '9.99', '168');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('148', 'Cushion Covers', '35', '89');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('149', 'Graphic Hoodie', '49.99', '26');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('150', 'Baked Falafel Balls', '5.99', '99');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('151', 'Vegan Alfredo Sauce', '4.99', '146');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('152', 'Silicone Baking Molds', '15.99', '103');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('153', 'Customizable Photo Calendar', '19.99', '111');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('154', 'Fitness Activity Journal', '14.99', '69');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('155', 'Dog Car Seat Cover', '39.99', '84');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('156', 'Pumpkin Spice Pancake Mix', '3.49', '79');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('157', 'White Rice', '1.49', '64');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('158', 'Ginger Snaps', '2.79', '131');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('159', 'Classic Vanilla Fudge', '4.49', '105');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('160', 'Weighted Jump Rope', '15.99', '118');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('161', 'Sweet Corn', '1.5', '85');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('162', 'Leather Biker Jacket', '129.99', '68');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('163', 'Magnetic Whiteboard', '34.99', '194');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('164', 'Black Olives', '1.99', '56');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('165', 'Hot Dog Buns', '2.49', '51');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('166', 'Chocolate Covered Pretzels', '3.29', '64');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('167', 'Tennis Racket', '89.99', '72');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('168', 'Kids'' STEM Robotics Kit', '59.99', '100');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('169', 'Cheesy Broccoli Soup Mix', '2.99', '98');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('170', 'Pomegranate Juice', '4.49', '104');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('171', 'Roasted Red Pepper Sauce', '3.29', '97');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('172', 'Brazil Nuts', '10.99', '96');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('173', 'Organic Black Rice', '3.59', '163');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('174', 'Chickpea Pancakes', '4.99', '111');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('175', 'Breezy Off-The-Shoulder Top', '34.99', '109');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('176', 'Camping Tarp', '32.99', '148');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('177', 'Herbed Goat Cheese', '5.49', '112');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('178', 'Rice Pudding', '2.29', '105');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('179', 'Snap-On Tupperware Set', '34.99', '100');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('180', 'Pumpkin Pie Spice', '2.99', '72');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('181', 'Sun-Dried Tomatoes', '3.99', '63');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('182', 'Whole Roasted Chicken', '9.99', '87');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('183', 'Pasta (Fusilli)', '1.79', '99');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('184', 'Bicycle Repair Kit', '14.99', '86');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('185', 'Herbed Couscous', '2.49', '63');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('186', 'Electric Opener for Jars and Bottles', '24.99', '144');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('187', 'Car Phone Mount', '15.99', '93');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('188', 'Raspberry Limeade', '1.99', '108');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('189', 'Nutty Granola Clusters', '2.49', '87');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('190', 'Pet Nail Clipper', '12.99', '89');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('191', 'Window Bird Feeder with Suction Cups', '28.99', '84');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('192', 'Honey Garlic Sauce', '2.59', '151');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('193', 'Fruit Medley Juice', '3.49', '95');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('194', 'Smoked Paprika Chicken Thighs', '6.99', '137');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('195', 'Chili Beans (canned)', '1.69', '120');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('196', 'Coffee Maker', '89.99', '131');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('197', 'Sweet Potato Noodles', '3.79', '127');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('198', 'Grass Fed Beef Patties', '9.99', '182');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('199', 'Infrared Thermometer', '39.99', '51');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('200', 'Honey Roasted Almonds', '4.99', '28');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('201', 'Chili Beans in Sauce', '1.79', '100');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('202', 'Cranberry Pecan Granola', '3.99', '118');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('203', 'Hydration Backpack', '39.99', '67');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('204', 'Chili Lime Corn Chips', '2.79', '137');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('205', 'Spicy Chicken Wings', '9.99', '58');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('206', 'Traditional Hummus', '3.29', '72');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('207', 'Organic Spinach', '2.99', '147');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('208', 'Mini Indoor Herb Garden Kit', '24.99', '117');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('209', 'Cookbook', '27.99', '90');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('210', 'Coffee Grinder', '39.99', '136');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('211', 'Sweet Chili Thai Sauce', '3.49', '84');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('212', 'Wall-Mounted Organizer', '34.99', '74');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('213', 'Set of Silicone Baking Molds', '15.99', '104');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('214', 'Andouille Sausage', '5.49', '35');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('215', 'Overnight Duffle Bag', '34.99', '66');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('216', 'Cinnamon Sugar Mix', '1.49', '123');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('217', 'Wireless HDMI Receiver', '49.99', '102');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('218', 'Chic Jumpsuit', '89.99', '109');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('219', 'Coconut Chips', '3.59', '107');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('220', 'Wrap Jumpsuit', '54.99', '130');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('221', 'Self-Watering Planter', '24.99', '89');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('222', 'Professional Chef Knife', '89.99', '74');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('223', 'Electric Stir Fry Pan', '49.99', '72');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('224', 'Magic Color-Changing Mug', '14.99', '112');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('225', 'Repair Tool Set for Home Improvement', '29.99', '94');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('226', 'Travel Sewing Kit', '12.99', '91');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('227', 'Peanut Butter Pretzel Bites', '4.19', '91');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('228', 'Digital Bullet Journal', '24.99', '114');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('229', 'Tomatillo Salsa', '3.29', '54');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('230', 'Fitness Resistance Bands', '29.99', '133');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('231', 'Brownie Bites', '4.99', '72');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('232', 'Organic Tomato Soup', '3.79', '32');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('233', 'Vegan Caesar Dressing', '3.99', '104');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('234', 'Customizable Name Puzzle', '29.99', '109');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('235', 'Fishing Rod', '49.99', '87');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('236', 'Pet Bed', '39.99', '125');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('237', 'Coffee Subscription Service', '29.99', '135');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('238', 'Cranberry Lime Sparkling Water', '1.5', '100');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('239', 'Mango Chutney', '3.99', '182');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('240', 'Personalized Cutting Board', '34.99', '66');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('241', 'Frozen Acai Purée', '6.99', '116');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('242', 'Almond Butter', '6.49', '53');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('243', 'Deluxe First Aid Kit', '39.99', '93');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('244', 'Italian Sausage Links', '5.99', '116');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('245', 'Mediterranean Flatbread', '3.5', '96');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('246', 'Wall Decals for Kids', '24.99', '110');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('247', 'Toilet Paper (12 rolls)', '8.99', '60');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('248', 'Inflatable Party Cooler', '19.99', '91');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('249', 'Chocolate Fudge Ice Cream', '5.99', '105');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('250', 'Garlic Naan Bread', '3.99', '149');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('251', 'Decorative Wall Tapestry', '34.99', '85');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('252', 'Luxury Yoga Mat', '39.99', '108');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('253', 'Peach Mango Smoothie Mix', '5.99', '33');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('254', 'Personal Safety Alarm', '12.99', '92');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('255', 'Electric Hot Water Dispenser', '59.99', '99');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('256', 'Vanilla Protein Powder', '24.99', '61');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('257', 'Essential Oil Roller Bottles', '19.99', '83');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('258', 'Kids'' Craft Supplies Set', '24.99', '78');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('259', 'Ergonomic Gaming Chair', '199.99', '95');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('260', 'Chipotle Black Bean Salad', '3.29', '77');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('261', 'Artisan Bread Loaf', '3.99', '115');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('262', 'Cucumber Relish', '3.39', '154');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('263', 'Herbed Chicken Breast', '7.99', '128');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('264', 'Maple Almond Granola', '5.49', '113');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('265', 'Sweet and Spicy Barbecue Sauce', '3.99', '64');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('266', 'Yoga Mat', '25', '81');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('267', 'Air Purifier', '129.99', '107');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('268', 'Puffed Rice Cake', '2.49', '101');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('269', 'Survival Gear Kit', '59.99', '107');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('270', 'Zucchini Noodle Pasta', '3.99', '112');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('271', 'Salsa Verde', '3.49', '111');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('272', 'Portable Air Pump', '19.99', '76');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('273', 'Smart Home Security Camera', '79.99', '105');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('274', 'Sliced Olives', '1.99', '107');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('275', 'Sturdy Bookends', '22.99', '70');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('276', 'Casual Sneakers', '39.99', '128');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('277', 'Cinnamon Raisin Bagels', '4.19', '69');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('278', 'Truffle Parmesan Fries', '4.99', '155');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('279', 'Banana Nut Oatmeal Cups', '2.99', '133');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('280', 'LED Desk Light', '34.99', '132');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('281', 'Mini Indoor Hydroponic Garden', '59.99', '70');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('282', 'Chopping Board', '29.99', '67');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('283', 'Dog Waste Bag Dispenser', '6.99', '144');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('284', 'Gardening Tools Set', '45', '57');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('285', 'Vegetable Korma', '6.49', '153');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('286', 'Pet Training Clicker', '5.99', '83');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('287', 'Chocolate Mint Cookies', '2.29', '110');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('288', 'Sports Water Bottle with Infuser', '19.99', '78');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('289', 'Over-the-Door Shoe Organizer', '22.99', '51');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('290', 'Blackberry Jam', '4.29', '48');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('291', 'Crispy Tofu Bites', '4.99', '167');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('292', 'Vanilla Almond Granola', '4.29', '146');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('293', 'Whisk Set', '12.99', '79');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('294', 'Pasta Portion Control Measure', '9.99', '48');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('295', 'Gardening Tool Belt', '22.99', '77');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('296', 'Smart Water Bottle with Hydration Reminder', '39.99', '168');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('297', 'Vegan chocolate chip cookies', '4.79', '75');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('298', 'Reusable Produce Bags Set', '14.99', '107');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('299', 'Safety First Aid Kit', '29.99', '84');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('300', 'Gardening Gloves', '15.99', '106');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('301', 'Glass Tea Pot', '34.99', '153');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('302', 'Pet Water Fountain with Filtration', '39.99', '103');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('303', 'Pressure Cooker', '89', '128');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('304', 'Spiced Pumpkin Soup', '3.99', '89');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('305', 'Garam Masala Spice Blend', '2.79', '117');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('306', 'Blueberry Chia Jam', '4.99', '81');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('307', 'Stainless Steel Mixing Bowls', '29.99', '67');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('308', 'Frozen Hash Browns', '2.99', '62');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('309', 'Almond Flour Tortillas', '4.99', '100');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('310', 'Pear and Gorgonzola Salad', '5.49', '64');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('311', 'Chewy Granola Bars', '3.49', '84');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('312', 'Beef Tacos', '5.49', '107');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('313', 'Pumpkin Spice Creamer', '3.79', '127');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('314', 'Ice Cube Tray with Lid', '10.99', '77');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('315', 'Laptop Backpack', '69.99', '147');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('316', 'Outdoor Camping Hammock', '29.99', '52');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('317', 'Car Windshield Sun Shade', '19.99', '117');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('318', 'Hummus', '4.29', '136');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('319', 'Cotton Tote Bag Set', '29.99', '109');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('320', 'Fitness Tracker with Heart Rate Monitor', '59.99', '30');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('321', 'Bamboo Cotton Tank Top', '22.99', '53');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('322', 'Digital Photo Frame', '79.99', '122');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('323', 'Heated Throw Blanket', '49.99', '98');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('324', 'Pet Hair Vacuum Cleaner Attachment', '14.99', '125');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('325', 'Adjustable Pedicure Footrest', '39.99', '130');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('326', 'High-Quality Yoga Block', '12.99', '81');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('327', 'Apricot Jam', '4.29', '56');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('328', 'Watercolor Set', '19.99', '70');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('329', 'Nut Butter Cups', '3.99', '86');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('330', 'Pasta Maker Machine', '59.99', '89');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('331', 'Smartphone Tripod', '29.99', '122');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('332', 'LED Makeup Mirror', '39.99', '88');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('333', 'Kettle Corn Popcorn', '2.99', '165');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('334', 'Sports Bottle', '15.99', '100');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('335', 'Frozen Berry Medley', '5.49', '106');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('336', 'Slingback Sandals', '29.99', '115');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('337', 'Chocolate Chip Cookie Mix', '2.49', '134');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('338', 'Lasagna Noodles', '1.89', '104');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('339', 'V-Neck Sweater', '49.99', '112');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('340', 'Peanut Butter Granola', '4.99', '92');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('341', 'Biodegradable Dog Waste Bags', '14.99', '120');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('342', 'Shredded Cheese', '4.29', '69');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('343', 'Pet Activity Tracker', '59.99', '95');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('344', 'Roasted Vegetable Medley', '3.99', '113');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('345', 'Radish Chips', '2.89', '79');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('346', 'Personal Blender with Travel Lid', '34.99', '86');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('347', 'Kale Salad Kit', '4.99', '74');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('348', 'Smart Plant Monitor', '24.99', '126');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('349', 'Chili Lime Seasoning', '2.99', '117');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('350', 'Protein Bar Variety Pack', '12.99', '116');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('351', 'Induction Cooktop', '89.99', '36');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('352', 'Athletic Jogging Jacket', '49.99', '147');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('353', 'Sesame Garlic Noodles', '3.49', '46');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('354', 'Creamy Coleslaw Mix', '2.39', '127');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('355', 'Sustainable Wooden Toys', '29.99', '146');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('356', 'Chocolate Hazelnut Granola', '4.49', '62');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('357', 'Wireless Earbuds', '69.99', '107');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('358', 'Portable Water Filter', '29.99', '101');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('359', 'Fashionable Scarves Set', '24.99', '69');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('360', 'Caraway Rye Bread', '4.79', '136');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('361', 'Essential White Button-Up', '44.99', '107');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('362', 'Instant Read Meat Thermometer', '24.99', '112');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('363', 'Asian Noodle Salad Kit', '4.99', '109');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('364', 'Almond Crunch Granola Bars', '3.49', '44');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('365', 'Indian Curry Sauce', '3.69', '105');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('366', 'Self-Watering Planters', '49.99', '173');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('367', 'Buffalo Cauliflower Bites', '6.29', '72');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('368', 'Ceramic Cookware Set', '179.99', '107');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('369', 'Organic Green Tea', '4.29', '157');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('370', 'Garden Hose Reel', '49.99', '83');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('371', 'Curried Lentil Salad', '4.29', '64');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('372', 'Kids'' Activity Book', '14.99', '109');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('373', 'Set of Gardening Gloves with Claws', '15.99', '69');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('374', 'Coloring Books for Adults', '14.99', '154');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('375', 'Pet Carrier Backpack', '39.99', '108');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('376', 'DIY Lip Balm Making Kit', '22.99', '103');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('377', 'Tomato Basil Pasta Sauce', '3.99', '119');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('378', 'Sunflower Seeds', '2.99', '154');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('379', 'High-Waisted Skirt', '34.99', '74');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('380', 'Insulated Lunch Box', '24.99', '129');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('381', 'Whole Grain Cereal', '3.49', '108');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('382', 'A-Line Skirt', '35.99', '157');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('383', 'Honey Butter Popcorn', '2.99', '91');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('384', 'Sweetened Condensed Milk', '1.89', '112');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('385', 'Sea Salt Caramel Popcorn', '3.99', '140');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('386', 'Sliced Cucumbers', '1.29', '70');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('387', 'Yoga Blocks', '29.99', '87');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('388', 'Cotton Pajama Set', '49.99', '161');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('389', 'Wireless Security Camera', '109.99', '145');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('390', 'Zesty Garlic Marinade', '4.49', '114');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('391', 'Classic Pumps', '64.99', '101');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('392', 'Chickpea Flour', '3.29', '122');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('393', 'Memory Card', '15.99', '91');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('394', 'Floral Wrap Top', '49.99', '114');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('395', 'Peach Yogurt', '1.29', '146');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('396', 'Paint By Numbers Kit', '24.99', '128');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('397', 'Vegetarian Pizza', '5.49', '82');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('398', 'Lemon Herb Chicken', '7.49', '116');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('399', 'BBQ Jackfruit', '4.29', '128');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('400', 'Fruit Infuser Water Bottle', '15.99', '52');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('401', 'Electric Wine Opener', '29.99', '97');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('402', 'Sunglasses', '29.99', '163');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('403', 'Spinach Pizza Rolls', '4.99', '83');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('404', 'Oversized Denim Shirt', '49.99', '110');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('405', 'Underwater Camera', '199.99', '80');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('406', 'Eco-Friendly Beeswax Wraps', '14.99', '47');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('407', 'Mango Salsa', '3.49', '71');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('408', 'Wall Art', '45', '101');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('409', 'Mediterranean Chickpea Salad', '5.99', '129');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('410', 'Pecan Nuts', '6.49', '67');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('411', 'Spicy Roasted Nuts', '4.99', '112');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('412', 'Popcorn Chicken', '6.49', '128');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('413', 'Sea Salt Caramel Brownie', '2.49', '70');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('414', 'Portable Camping Shower', '39.99', '63');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('415', 'Electric Blanket', '59.99', '57');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('416', 'LED Flashing Pet Collar', '14.99', '131');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('417', 'Falafel Mix', '2.79', '125');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('418', 'Instant Pot', '89.99', '149');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('419', 'Denim Jacket', '69.99', '78');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('420', 'Stuffed Bell Peppers', '5.99', '125');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('421', 'Vegan Mayonnaise', '4.49', '87');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('422', 'Nut Mix', '5.99', '113');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('423', 'Portable Blender', '30', '114');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('424', 'Bamboo Utensil Holder', '14.99', '107');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('425', 'Memory Foam Mattress Topper', '109.99', '193');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('426', 'Vegetable Quinoa Bowl', '5.99', '69');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('427', 'Dark Chocolate Covered Raisins', '3.99', '23');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('428', 'Balsamic Vinegar', '4.99', '124');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('429', 'Herbal Garden Starter Kit', '24.99', '159');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('430', 'Oven Mitts', '15.99', '37');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('431', 'Handmade Wooden Utensil Set', '24.99', '87');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('432', 'Frozen Pizza', '7.99', '82');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('433', 'Thai Red Curry Paste', '3.99', '99');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('434', 'Lightweight Workout Tank', '29.99', '43');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('435', 'Chocolate Chip Pancake Mix', '3.99', '183');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('436', 'Over-Ear Headphones', '59.99', '93');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('437', 'Electric Heat Pad', '24.99', '174');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('438', 'Fashionable Fanny Pack', '24.99', '100');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('439', 'Low-Fat Cottage Cheese', '2.99', '82');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('440', 'Almond Butter Granola Bars', '4.99', '143');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('441', 'Handheld Vacuum', '79.99', '133');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('442', 'Kids'' Dinosaur-Themed Lunchbox', '19.99', '23');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('443', 'Travel Jewelry Organizer', '19.99', '111');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('444', 'Hiking Gaiters', '29.99', '97');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('445', 'Smart Fitness Scale', '49.99', '101');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('446', 'Ramen Noodles', '0.99', '88');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('447', 'Adjustable Resistance Bands', '39.99', '78');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('448', 'Buttermilk Pancakes', '3.99', '161');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('449', 'Nutty Quinoa Salad', '4.99', '68');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('450', 'Honey Sriracha Chicken Bites', '7.99', '113');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('451', 'Beard Grooming Kit', '34.99', '85');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('452', 'Pumpkin Spice Cookies', '3.29', '98');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('453', 'Smartphone Stand', '15.49', '105');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('454', 'Dish Soap Dispenser', '18.99', '83');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('455', 'Asian Stir-Fry Vegetables', '2.99', '104');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('456', 'Lemon Basil Pasta Sauce', '4.99', '107');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('457', 'Sushi Roll Kit', '9.99', '126');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('458', 'Pet Hair Removal Brush', '14.99', '155');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('459', 'Elegant Lace Dress', '79.99', '50');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('460', 'Compact Hair Dryer', '29.99', '82');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('461', 'Fitness Smartwatch', '99.99', '146');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('462', 'Classic Bagels', '2.99', '122');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('463', 'Photo Album', '24.99', '163');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('464', 'Sweet BBQ Dipping Sauce', '3.49', '139');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('465', 'Sweet and Sour Sauce', '2.79', '80');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('466', 'LED Desk Lamp', '35', '164');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('467', 'Digital Food Scale', '22.99', '84');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('468', 'Savory Oatmeal Cups', '1.99', '65');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('469', 'Crispy Potato Tots', '3.69', '61');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('470', 'Inflatable Paddle Board', '349.99', '79');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('471', 'Travel Yoga Mat', '34.99', '57');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('472', 'Chunky Knit Sweater', '59.99', '120');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('473', 'Baked Potato Chips', '2.49', '84');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('474', 'Weighted Blanket', '79.99', '141');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('475', 'Pork Chops', '9.49', '60');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('476', 'Travel Jewelry Case', '24.99', '91');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('477', 'Baking Powder', '1.79', '130');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('478', 'Scented Candle Set', '24.99', '82');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('479', 'Non-Toxic Concrete Sealer', '39.99', '171');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('480', 'Teriyaki Tofu Stir-Fry', '7.49', '76');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('481', 'Classic Chicken Noodle Soup', '3.49', '64');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('482', 'Wireless Smart Plug', '19.99', '124');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('483', 'Fitness Resistance Bands Set', '34.99', '127');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('484', 'Personal Blender with Cups', '34.99', '94');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('485', 'Sweet Chili Dipping Sauce', '2.99', '88');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('486', 'LED Strip Lights with Remote Control', '29.99', '119');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('487', 'Fishing Tackle Box', '24.99', '124');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('488', 'Savory Oatmeal', '2.49', '90');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('489', 'Frozen Berry Blend', '4.99', '105');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('490', 'Adjustable Laptop Stand', '29.99', '99');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('491', 'Gardening Fairy Figurines', '14.99', '91');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('492', 'Adjustable Dog Harness', '24.99', '55');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('493', 'Organic Coconut Water', '2.79', '160');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('494', 'Silicone Ice Cube Tray', '10.99', '105');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('495', 'Apple Cinnamon Oatmeal', '2.89', '55');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('496', 'Foldable Picnic Table', '49.99', '66');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('497', 'Handmade Leather Journal', '39.99', '101');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('498', 'Vegetarian Stir Fry Sauce', '2.49', '106');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('499', 'Wooden Toy Train Set', '29.99', '41');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('500', 'Strawberry Rhubarb Jam', '4.29', '152');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('501', 'Spicy Italian Sausage', '4.99', '65');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('502', 'Set of Herb Garden Markers', '8.99', '106');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('503', 'Noise Reduction Headphones', '39.99', '143');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('504', 'Cacao Nibs', '6.49', '143');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('505', 'Honey mustard chicken tenders', '7.99', '112');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('506', 'Terry Cloth Robe', '59.99', '78');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('507', 'Active Racerback Tank', '24.99', '48');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('508', 'Rechargeable Hand Warmer', '22.99', '74');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('509', 'Car Vacuum', '49.99', '54');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('510', 'Pineapple Salsa', '4.29', '138');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('511', 'Chocolate Coconut Protein Balls', '2.99', '128');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('512', 'Pumpkin Seeds', '2.79', '28');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('513', 'Self-Stirring Mug', '19.99', '53');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('514', 'Motion Sensor Light', '19.99', '100');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('515', 'Pineapple Coconut Yogurt', '4.49', '99');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('516', 'Portable Electric Fan', '24.99', '127');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('517', 'Striped Long Sleeve Shirt', '29.99', '115');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('518', 'Outdoor Folding Table', '39.99', '140');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('519', 'Stainless Steel BBQ Grill Set', '49.99', '114');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('520', 'Portable Air Purifier', '69.99', '76');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('521', 'Foot Massager', '79.99', '147');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('522', 'Solar Garden Lights', '39.99', '90');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('523', 'Organic Cereal Bars', '4.29', '94');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('524', 'Gluten-Free Pancake Mix', '5.99', '112');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('525', 'Dog Training Clicker', '5.99', '74');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('526', 'Chocolate Chip Muffins', '3.99', '127');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('527', 'Elderberry Syrup', '11.99', '104');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('528', 'Tofu', '2.49', '110');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('529', 'Trail Mix (Deluxe)', '4.59', '127');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('530', 'Caramelized Onion Dip', '3.99', '145');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('531', 'Decorative Throw Pillows', '29.99', '107');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('532', 'Chia Seeds', '6.99', '97');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('533', 'Smart Thermos', '39.99', '130');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('534', 'Organic Green Lentils', '3.99', '103');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('535', 'Garlic Herb Marinade', '3.29', '107');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('536', 'Trackpad for Laptop', '49.99', '60');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('537', 'Hair Dryer', '39.99', '66');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('538', 'Toy Building Set', '29.99', '77');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('539', 'Almond Quinoa Salad', '5.99', '96');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('540', 'LED Christmas Tree Lights', '34.99', '148');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('541', 'Portable Hammock Swing', '59.99', '88');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('542', 'Cheesy Cauliflower Bake', '5.49', '63');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('543', 'Mushrooms', '2.99', '106');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('544', 'Reusable Food Storage Bags', '19.99', '70');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('545', 'Robot Vacuum Cleaner', '299.99', '121');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('546', 'Italian Breadsticks', '2.49', '76');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('547', 'Adjustable Height Standing Desk Converter', '89.99', '103');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('548', 'LED Strip Lights Kit', '29.99', '99');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('549', 'Teriyaki Chicken Stir-Fry', '6.99', '96');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('550', 'Dog Training Whistle', '8.99', '90');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('551', 'Smart Light Switch', '29.99', '99');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('552', 'Chocolate Avocado Pudding', '4.99', '132');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('553', 'Measuring Cups Set', '19.99', '29');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('554', 'Cucumber Lime Sparkling Water', '1.49', '109');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('555', 'Free-Range Eggs', '3.99', '130');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('556', 'Whole Grain Hamburger Buns', '2.69', '64');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('557', 'Hibiscus Tea Bags', '3.79', '166');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('558', 'Frozen Vegetarian Pizza', '6.49', '90');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('559', 'Cheddar Cheese Slices', '3.49', '95');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('560', 'Pet Travel Backpack Carrier', '49.99', '153');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('561', 'Pet Tracking Collar', '59.99', '77');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('562', 'Electric Rice Cooker with Steamer', '49.99', '80');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('563', 'Travel Luggage Scale', '14.99', '126');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('564', 'Peas (frozen)', '1.89', '114');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('565', 'Homestyle Chicken Noodle Soup', '2.99', '97');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('566', 'Maple Breakfast Sausage', '5.99', '174');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('567', 'Car Diagnostic Scanner', '49.99', '58');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('568', 'Heat-Resistant Silicone Mat', '19.99', '83');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('569', 'Kale Chips', '3.99', '71');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('570', 'Digital Voice Recorder', '49.99', '135');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('571', 'Nordic Berry Smoothie', '3.99', '68');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('572', 'Sweet Potatoes', '0.89', '131');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('573', 'Vintage Button-Down Shirt', '45.99', '162');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('574', 'Balsamic Glaze', '4.79', '114');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('575', 'Portable Charcoal Grill', '89.99', '103');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('576', 'Savory Mushroom Risotto', '6.49', '169');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('577', 'Folding Table', '59.99', '110');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('578', 'Low-Fat Yogurt', '3.29', '119');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('579', 'Mango Chilli Sauce', '3.99', '78');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('580', 'Vacuum Sealer Machine', '89.99', '94');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('581', 'Reusable Coffee Filter', '10.99', '31');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('582', 'Adjustable Pet Feeder', '39.99', '95');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('583', 'Maple Cinnamon Granola', '4.29', '73');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('584', 'Car Escape Tool', '12.99', '96');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('585', 'Bamboo Memory Foam Pillow', '34.99', '98');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('586', 'Smart Thermostat with Wi-Fi', '169.99', '95');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('587', 'Folding Backpack Chair', '49.99', '66');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('588', 'Magnetic Spice Jars', '24.99', '110');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('589', 'Multi-Function Smartphone Holder', '12.99', '140');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('590', 'Dishwasher Safe Cutting Board', '22.99', '155');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('591', 'Slim Fit Chinos', '54.99', '71');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('592', 'Rechargeable Laptop Battery Pack', '49.99', '88');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('593', 'Mini Food Processor', '39.99', '66');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('594', 'Portable Laptop Table', '39.99', '79');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('595', 'Sweet Potato and Chickpea Bowl', '6.49', '105');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('596', 'Stuffed Grape Leaves', '5.79', '32');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('597', 'Smart Plug', '19.99', '62');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('598', 'Lemon Herb Quinoa', '3.49', '109');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('599', 'Coconut Bowls Set', '22.99', '82');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('600', 'Vegetable Chips', '3.99', '55');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('601', 'Graphic Tee', '19.99', '62');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('602', 'Granola Cereal', '4.49', '44');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('603', 'Adjustable Bar Stools', '149.99', '114');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('604', 'Manual Coffee Grinder', '22.99', '121');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('605', 'Eggs (dozen)', '2.99', '51');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('606', 'Ceramic Bakeware Set', '49.99', '38');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('607', 'Elderberry Syrup Kit', '22.99', '117');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('608', 'Stylish Combat Boots', '99.99', '119');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('609', 'Herbal Tea Infuser', '9.99', '115');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('610', 'Canvas Wall Art', '39.99', '70');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('611', 'Cat Scratching Post with Toys', '44.99', '51');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('612', 'Ramen Noodle Soup Cups', '1.29', '136');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('613', 'Teriyaki Chicken Bowl', '6.49', '119');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('614', 'Herb Seasoned Couscous', '2.49', '95');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('615', 'Reusable Silicone Food Storage Bags', '19.99', '131');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('616', 'Camping Chair with Cooler', '49.99', '111');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('617', 'Silicone Baking Mat Set', '24.99', '123');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('618', 'Tea Set with Infuser', '34.99', '77');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('619', 'Coconut Chia Seed Pudding', '2.99', '23');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('620', 'Nail Polish Set', '25', '99');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('621', 'Spinach and Cheese Stuffed Shells', '5.99', '36');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('622', 'Silicone Baking Cups', '10.99', '84');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('623', 'Portable Bluetooth Speaker', '49.99', '107');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('624', 'Organic Coconut Sugar', '4.19', '90');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('625', 'Rice Pilaf Mix', '2.59', '114');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('626', 'Herb-Infused Olive Oil', '8.99', '128');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('627', 'Dark Chocolate Almond Butter Cups', '4.99', '76');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('628', 'Gingerbread House Kit', '6.99', '141');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('629', 'Self-Adhesive Wallpaper', '34.99', '111');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('630', 'Lemon Dill Chicken Skewers', '9.99', '66');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('631', 'Compact Refrigerator', '199.99', '62');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('632', 'Canvas Tote Bag', '19.99', '76');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('633', 'Matcha Green Tea Powder', '14.99', '110');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('634', 'Sriracha Chili Sauce', '2.79', '25');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('635', 'Pumpkin Spice Coffee', '7.99', '73');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('636', 'Mayonnaise', '3.29', '100');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('637', 'Reusable Snack Bags', '14.99', '103');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('638', 'Almond Butter Cookies', '4.49', '98');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('639', 'High-Speed Hand Blender', '39.99', '123');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('640', 'Nature Explorer Lens Kit', '19.99', '81');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('641', 'Flavored Popcorn Mix', '2.99', '110');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('642', 'Silicone Cooking Utensils Set', '34.99', '82');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('643', 'Compact Shoe Rack', '34.99', '68');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('644', 'Magnetic Curtain Tiebacks', '12.99', '103');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('645', 'Coconut Cream Pie Yogurt', '1.99', '148');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('646', 'Honey Roasted Chickpeas', '3.29', '147');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('647', 'Spaghetti Sauce', '2.99', '134');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('648', 'Wooden Blocks', '24.99', '58');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('649', 'Habanero Hot Sauce', '3.79', '60');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('650', 'Suction Cup Hooks', '9.99', '61');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('651', 'Lemon Lime Sparkling Water', '1.99', '128');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('652', 'Cranberry Almond Granola', '4.29', '64');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('653', 'Chili Con Carne Mix', '2.99', '141');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('654', 'Organic Black Bean Burger', '4.49', '138');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('655', 'Ribbed Knit Dress', '59.99', '78');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('656', 'Mixed Nuts', '5.99', '145');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('657', 'Throw Pillow Covers', '22.99', '137');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('658', 'Roasted Red Pepper Dip', '3.29', '68');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('659', 'Pork Tenderloin', '10.99', '99');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('660', 'Whole Wheat Pasta', '2.49', '72');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('661', 'Organic Ramen Noodles', '2.89', '54');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('662', 'Cranberry Orange Oatmeal', '2.49', '115');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('663', 'Ankle Boots', '89.99', '87');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('664', 'Coconut Granola', '4.19', '117');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('665', 'Spicy BBQ Sauce', '3.99', '83');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('666', 'Adjustable Stand for Tablets and Smartphones', '19.99', '73');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('667', 'Stuffed Peppers with Quinoa', '7.99', '149');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('668', 'Portable Charger with Solar Panel', '45.99', '70');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('669', 'Strawberry Fruit Spread', '3.59', '99');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('670', 'Organic Cucumber', '1.29', '145');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('671', 'Dried Apricots', '3.79', '118');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('672', 'Organic Granola Cereal', '5.99', '71');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('673', 'Sports Windbreaker', '44.99', '87');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('674', 'Coconut Almond Granola', '4.99', '83');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('675', 'Lentils', '2.99', '106');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('676', 'Coconut Milk Ice Cream', '6.99', '21');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('677', 'Sriracha Sauce', '3.19', '105');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('678', 'Pesto Pasta Sauce', '3.99', '68');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('679', 'Pet Grooming Scissors', '16.99', '87');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('680', 'Blender Bottle', '12.99', '87');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('681', 'Infrared Thermometer Gun', '29.99', '136');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('682', 'Elegant Maxi Skirt', '44.99', '28');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('683', 'Lentil Soup (canned)', '1.99', '80');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('684', 'Two-Tier Fruit Basket', '29.99', '74');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('685', 'Floral Summer Dress', '39.99', '103');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('686', 'Pet Hair Remover', '9.99', '96');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('687', 'Travel Pillow', '22.99', '94');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('688', 'Crispy Kale Chips', '2.99', '104');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('689', 'Spicy Salsa Verde', '3.49', '48');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('690', 'Kid''s Fruit Snacks', '2.49', '120');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('691', 'Cat Tree', '99.99', '69');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('692', 'Guitar Tuner', '19.99', '126');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('693', 'Artisan Cornbread Mix', '2.49', '59');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('694', 'Herb Garden Planter Box', '49.99', '76');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('695', 'Portable Speaker Stand', '39.99', '27');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('696', 'Black Bean Salsa', '3.49', '121');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('697', 'Frozen Acai Bowl', '6.49', '97');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('698', 'Patterned Knit Scarf', '25.99', '86');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('699', 'Wireless Mouse', '25.99', '137');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('700', 'Jalapeño Cornbread', '3.29', '85');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('701', 'Berries Medley', '6.99', '144');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('702', 'Outdoor Mosquito Repellent Lantern', '34.99', '112');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('703', 'Herb Drying Rack', '22.99', '97');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('704', 'Cauliflower Crust Pizza', '7.99', '71');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('705', 'Blueberry Muffin Mix', '4.29', '82');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('706', 'Coconut Lime Rice', '2.99', '35');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('707', 'Durable Hiking Boots', '89.99', '97');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('708', 'Chipotle Seasoning Blend', '2.49', '88');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('709', 'Magnet Travel Fridge Magnets', '12.99', '154');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('710', 'Bird Feeder', '24.99', '129');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('711', 'Sporty Leggings', '39.99', '135');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('712', 'Stainless Steel Travel Mug', '19.99', '106');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('713', 'Backpack', '49.99', '92');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('714', 'Multi-Cooker', '89.99', '124');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('715', 'Smart Scale', '59.99', '121');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('716', 'Leek and Potato Soup', '3.29', '141');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('717', 'Black Bean & Corn Salad', '3.99', '71');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('718', 'Turkey Bacon', '3.99', '95');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('719', 'Fall-Themed Table Runner', '19.99', '98');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('720', 'Set of Decorative Storage Bins', '34.99', '84');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('721', 'Poppy Seed Dressing', '3.49', '180');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('722', 'Garlic Parmesan Roasted Potatoes', '3.99', '119');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('723', 'Mini Hand Gesture Drone', '29.99', '86');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('724', 'Mango Chunks', '4.89', '194');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('725', 'Infrared Space Heater', '99.99', '115');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('726', 'Honey Sesame Chicken Mix', '8.99', '122');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('727', 'Kale Caesar Salad Kit', '5.99', '119');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('728', 'Herb Seasoned Croutons', '2.99', '129');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('729', 'Vegetarian Sausage Links', '5.89', '117');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('730', 'Faux Leather Leggings', '49.99', '112');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('731', 'Car Vacuum Cleaner', '39.99', '113');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('732', 'Tortilla Chips', '2.99', '78');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('733', 'Compact Dishwasher', '299.99', '54');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('734', 'Cooking Utensil Set', '24.99', '103');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('735', 'Vegetable Stir-Fry Kit', '6.99', '135');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('736', 'Miso Soup Starter', '2.99', '98');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('737', 'Pumpkin Spice Muffins', '3.99', '66');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('738', 'Maple Almond Yogurt', '1.89', '158');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('739', 'Salt and Pepper Grinder Set', '19.99', '89');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('740', 'Thermostatic Shower Valve Kit', '39.99', '99');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('741', 'Raspberry Vanilla Greek Yogurt', '3.49', '166');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('742', 'Fitbit Activity Tracker', '99.99', '107');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('743', 'Art Supplies Organizer', '18.99', '110');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('744', 'Frozen Burritos', '8.99', '129');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('745', 'Honey Sesame Cashews', '4.49', '91');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('746', 'Organic Granola', '5.49', '86');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('747', 'Children''s Art Set', '34.99', '112');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('748', 'Electric Food Slicer', '99.99', '78');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('749', 'Raisin Cinnamon Granola', '3.79', '109');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('750', 'Colorful Post-It Notes Set', '9.99', '90');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('751', 'Miso Soup Mix', '3.29', '91');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('752', 'Classic Caesar Salad Kit', '4.99', '74');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('753', 'Trendy Bomber Jacket', '69.99', '97');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('754', 'Sesame Seeds', '1.99', '106');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('755', 'Smartphone Car Mount with Wireless Charging', '39.99', '151');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('756', 'Wireless Induction Charger', '19.99', '128');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('757', 'Travel Beach Blanket', '29.99', '103');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('758', 'Heart-Shaped Baking Molds', '10.99', '84');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('759', 'Pet Water Fountain', '39.99', '79');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('760', 'Gluten-Free Brownies', '4.99', '122');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('761', 'Mesh Laundry Bags Set', '12.99', '68');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('762', 'Sporty Cap', '15.99', '147');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('763', 'Biodegradable Phone Case', '23.99', '69');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('764', 'Wildflower Honey', '4.99', '138');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('765', 'Roasted Garlic', '4.29', '115');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('766', 'Safety Goggles', '14.99', '80');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('767', 'Savory Breakfast Sausage', '6.49', '88');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('768', 'Portable Solar Path Lights', '39.99', '84');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('769', 'Fitness Balance Ball', '24.99', '101');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('770', 'Pleated Midi Dress', '79.99', '103');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('771', 'Carrot Sticks', '2.49', '80');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('772', 'Lentil Soup', '2.49', '144');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('773', 'Portable Solar Generator', '399.99', '135');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('774', 'Teriyaki Chicken Wings', '10.99', '75');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('775', 'Raspberry Tart', '5.49', '72');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('776', 'Spicy Tuna Sushi Kit', '8.99', '122');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('777', 'Greek Feta Cheese', '4.99', '65');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('778', 'Electric Wax Warmer', '22.99', '76');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('779', 'Children''s Musical Instrument Set', '39.99', '15');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('780', 'Vegetable Medley', '2.99', '102');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('781', 'Children''s Backpack', '29.99', '81');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('782', 'Caramelized Onion Dip Mix', '2.29', '92');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('783', 'Turmeric Ginger Tea', '3.29', '58');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('784', 'Wireless Car Charger', '24.99', '74');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('785', 'Foldable Yoga Mat', '29.99', '128');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('786', 'Creamy Ranch Dressing', '2.49', '148');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('787', 'Electric Food Steamer', '59.99', '165');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('788', 'Nutritional Yeast', '3.59', '131');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('789', 'Wall-Mounted Spice Rack', '39.99', '86');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('790', 'Non-Stick Baking Sheets', '29.99', '58');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('791', 'Smartphone UV Sanitizer', '39.99', '142');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('792', 'Pita Bread', '2.99', '71');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('793', 'Adjustable Dumbbells', '249.99', '82');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('794', 'Honey BBQ Riblets', '12.99', '69');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('795', 'Wireless Charging Station', '39.99', '73');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('796', 'Electric Pressure Cooker', '89.99', '104');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('797', 'Peanut Butter Pretzel Nuggets', '3.29', '170');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('798', 'Insulated Lunch Bag', '24.99', '155');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('799', 'Handcrafted Wooden Coasters', '19.99', '46');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('800', 'Vegetable Curry', '5.99', '68');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('801', 'Electric Toothbrush Holder', '14.99', '132');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('802', 'Beef Chili', '4.5', '118');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('803', 'Action Camera', '199.99', '47');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('804', 'Black Bean Spaghetti', '3.99', '169');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('805', 'Wireless Earbuds Case', '12.99', '133');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('806', 'Travel Eye Mask with Ear Plugs', '15.99', '110');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('807', 'Rustic Italian Bread', '3.59', '135');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('808', 'Travel Size Toiletry Bottles', '9.99', '105');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('809', 'Pet Travel Bed', '26.99', '132');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('810', 'Kids'' Outdoor Explorer Kit', '24.99', '117');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('811', 'Savory Italian Herbs', '2.99', '88');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('812', 'Pumpkin Spice Granola', '4.99', '76');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('813', 'Cheddar Cheese Crackers', '2.29', '107');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('814', 'Fitness Resistance Bands Kit', '29.99', '115');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('815', 'LED Flashlight with Rechargeable Batteries', '19.99', '106');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('816', 'Frozen Salmon Filets', '12.99', '95');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('817', 'Tactical Backpack', '59.99', '40');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('818', 'Self-Massaging Pillow', '49.99', '118');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('819', 'Home Karaoke System', '129.99', '71');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('820', 'Marinara Sauce', '3.49', '97');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('821', 'Thai Peanut Dressing', '3.29', '38');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('822', 'Roasted Garlic Butter', '3.29', '80');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('823', 'Peach Salsa', '3.29', '123');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('824', 'Chipotle Lime Salsa', '3.99', '83');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('825', 'Fitness Jump Rope with LCD Counter', '15.99', '103');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('826', 'Wi-Fi Enabled Smart Light Switch', '24.99', '49');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('827', 'Avocado Lime Dressing', '4.29', '107');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('828', 'Drone', '249.99', '53');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('829', 'Granulated Sugar', '2.49', '80');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('830', 'Travel Mug', '18.99', '135');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('831', 'Peach Slices in Syrup', '2.59', '106');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('832', 'Scent Diffuser Oil', '14.99', '99');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('833', 'Teriyaki Beef Strips', '7.49', '82');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('834', 'Fresh Basil Pesto', '4.79', '117');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('835', 'Oven-Baked Sweet Potato Fries', '3.99', '104');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('836', 'Outdoor Fire Pit', '149.99', '146');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('837', 'Skincare Fridge', '39.99', '109');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('838', 'Basic V-Neck T-Shirt', '19.99', '135');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('839', 'Bicycle Lock', '29.99', '129');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('840', 'Collapsible Water Bottle', '12.99', '175');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('841', 'Vegan Mac & Cheese', '8.99', '84');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('842', 'Maple Glazed Carrots', '3.29', '91');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('843', 'Plant-Based Meal Prep Containers', '18.99', '71');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('844', 'Orange Ginger Vinaigrette', '3.99', '49');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('845', 'Decorative Throw Blanket', '39.99', '68');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('846', 'Sliced Ham', '5.49', '156');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('847', 'BBQ Sauce', '3.49', '110');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('848', 'Portable Jump Starter', '59.99', '157');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('849', 'Outdoor Picnic Blanket', '34.99', '10');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('850', 'Electric Fondue Pot', '39.99', '56');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('851', 'Thai Peanut Noodles', '4.99', '87');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('852', 'Sweet Potato Mash', '3.99', '79');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('853', 'Egg Noodles', '2.29', '89');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('854', 'Bamboo Charcoal Air Purifier Bags', '12.99', '83');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('855', 'Maple Bacon Potato Chips', '2.89', '93');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('856', 'Silicone Wine Glasses', '22.99', '67');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('857', 'Portable Phone Charger', '29.99', '141');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('858', 'Portable Hammock', '27.99', '84');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('859', 'Basketball', '29.99', '63');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('860', 'Vegetable Pizza Rolls', '6.49', '70');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('861', 'Organic Almonds', '8.99', '94');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('862', 'Desk Organizer Set', '29.99', '65');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('863', 'Baking Soda', '0.99', '71');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('864', 'Luxury Rolling Makeup Case', '99.99', '110');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('865', 'Chocolate Chip Cookie Dough', '5.49', '103');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('866', 'Almond Butter Crunch Bar', '1.99', '73');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('867', 'Microwave Popcorn Maker', '19.99', '109');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('868', 'Ski Goggles', '49.99', '71');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('869', 'DIY Organic Gardening Kit', '39.99', '84');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('870', 'Shatterproof Wine Glasses', '24.99', '84');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('871', 'Puzzle Game Set', '34.99', '159');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('872', 'Spinach Feta Wraps', '4.29', '111');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('873', 'Sliced Cheese', '4.49', '149');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('874', 'Tomato Basil Soup', '3.49', '78');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('875', 'Portable Ice Maker', '199.99', '72');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('876', 'Ginger Turmeric Shots', '3.99', '28');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('877', 'Mini Projector', '169.99', '80');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('878', 'Banana Peanut Butter Smoothie', '5.49', '102');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('879', 'Blue Corn Tortilla Chips', '3.49', '37');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('880', 'Garlic Breadsticks', '3.49', '102');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('881', 'Handheld Shower Head', '34.99', '51');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('882', 'Red Lentil Pasta', '3.99', '99');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('883', 'Tuna Fish (canned)', '2.29', '115');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('884', 'Personalized Pet ID Tags', '9.99', '97');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('885', 'Thai Basil Fried Rice', '5.99', '118');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('886', 'Spicy Beef Taco Mix', '1.99', '80');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('887', 'High-Speed Blender', '99.99', '102');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('888', 'Interactive Plush Toy', '34.99', '129');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('889', 'Cinnamon Sugar Tortilla Chips', '3.29', '130');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('890', 'Classic Cheesecake Mix', '4.99', '130');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('891', 'Safety Pin Dispenser', '5.99', '80');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('892', 'Cinnamon Sugar Donuts', '4.99', '97');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('893', 'Juice Extractor', '99.99', '117');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('894', 'Creamy Tomato Basil Soup', '3.29', '125');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('895', 'Bluetooth Car Adapter', '24.99', '90');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('896', 'Coconut Milk Yogurt', '2.99', '185');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('897', 'Digital Thermostat', '59.99', '68');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('898', 'Organic Brown Sugar', '2.49', '78');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('899', 'Classic Cheeseburger Mix', '5.49', '113');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('900', 'High-Low Hem Tee', '22.99', '152');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('901', 'Honey Mustard Sauce', '3.29', '75');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('902', 'LED Under Cabinet Lighting', '29.99', '142');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('903', 'Wooden Children''s Play Kitchen', '129.99', '112');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('904', 'Almond Milk Yogurt', '1.99', '125');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('905', 'Pumpkin Puree', '2.99', '83');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('906', 'Solar String Lights', '29.99', '67');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('907', 'Bluetooth Shower Speaker', '24.99', '119');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('908', 'Lemon Zest Olive Oil', '8.99', '115');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('909', 'Electrolyte Water Bottle', '34.99', '99');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('910', 'Vegetable Lentil Soup', '3.49', '88');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('911', 'Sliced Bell Peppers', '3.99', '71');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('912', 'Smart Wi-Fi Light Bulbs', '19.99', '59');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('913', 'Rolling Cooler', '59.99', '77');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('914', 'Sous Vide Cooker', '79.99', '39');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('915', 'Kids'' Gardening Kit', '24.99', '90');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('916', 'Crispy Onion Rings', '4.29', '61');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('917', 'Dark Chocolate Covered Pretzels', '3.99', '30');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('918', 'Almond Flour Bread Mix', '4.89', '137');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('919', 'USB Flash Drive', '9.99', '58');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('920', 'Coconut Curry Lentil Soup', '3.99', '81');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('921', 'Balsamic Glazed Brussels Sprouts', '4.99', '116');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('922', 'Voice-Controlled Speaker', '99.99', '64');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('923', 'Skincare Set', '54.99', '84');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('924', 'Travel Organizer', '22.99', '161');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('925', 'LED Disco Ball Light', '19.99', '120');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('926', 'Thai Coconut Curry Sauce', '3.99', '93');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('927', 'Sporty Slide Sandals', '24.99', '120');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('928', 'Body Wash', '12.99', '122');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('929', 'Whipped Cream Cheese', '2.99', '89');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('930', 'Phone Case', '14.99', '155');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('931', 'Chicken Broth', '2.49', '113');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('932', 'Couscous Mix', '2.49', '77');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('933', 'Spicy Avocado Salsa', '4.49', '79');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('934', 'Bamboo Cutting Board Set', '34.99', '153');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('935', 'Roasted Garlic Pasta Sauce', '4.99', '120');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('936', 'Teriyaki Beef Jerky', '5.49', '73');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('937', 'Digital Food Thermometer', '19.99', '61');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('938', 'Compact Pop-Up Tent', '69.99', '96');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('939', 'DIY Lip Balm Kit', '22.99', '99');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('940', 'Tea Infuser Bottle', '19.99', '116');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('941', 'Soft Plush Throw Blanket', '29.99', '109');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('942', 'Wireless Gaming Headset', '89.99', '58');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('943', 'Pasta Primavera', '4.99', '82');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('944', 'Indoor Grill', '59.99', '59');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('945', 'Athletic Compression Tights', '39.99', '64');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('946', 'Cauliflower Gnocchi', '3.59', '127');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('947', 'Natural Fruit Snacks', '3.99', '117');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('948', 'Maple Almond Butter', '5.49', '96');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('949', 'Electric Butter Churn', '49.99', '113');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('950', 'USB Wall Charger', '19.99', '137');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('951', 'Garlic Parmesan Wings', '8.99', '80');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('952', 'Wrist Support Brace', '19.99', '72');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('953', 'Electric Stool Heater', '29.99', '89');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('954', 'Almond Flour Biscuits', '6.49', '74');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('955', 'Homestyle Beef Stew', '7.99', '92');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('956', 'Savory Pumpkin Soup', '3.89', '114');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('957', 'Self-Inflating Camping Mattress', '49.99', '92');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('958', 'Vegan Cheese', '4.99', '79');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('959', 'Honey Nut Cheerios', '4.29', '102');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('960', 'Honeycrisp Apples', '1.89', '87');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('961', 'Dog Training Collar', '39.99', '189');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('962', 'Electric Egg Cooker', '29.99', '136');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('963', 'Camping Tent', '79.99', '83');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('964', 'Greek Yogurt', '1.99', '39');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('965', 'Classic Black Dress', '79.99', '117');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('966', 'Smoked Paprika', '2.99', '99');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('967', 'Multicolored LED Strip Lights', '29.99', '152');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('968', 'Spicy Thai Chili Sauce', '3.29', '86');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('969', 'Bike Repair Tool Kit', '29.99', '111');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('970', 'Multi-Function Meat Tenderizer', '19.99', '139');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('971', 'Portable Leaf Blower', '149.99', '123');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('972', 'Electric Knife', '39.99', '101');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('973', 'Beef Enchilada Casserole', '8.99', '79');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('974', 'Cucumber', '0.99', '121');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('975', 'Digital Drawing Tablet', '79.99', '81');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('976', 'Outdoor Portable Fire Pit', '149.99', '68');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('977', 'Wireless Keyboard and Mouse Combo', '34.99', '42');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('978', 'Winter Knit Beanie', '14.99', '44');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('979', 'Classic Leather Wallet', '34.99', '115');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('980', 'Board Game Storage', '19.99', '135');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('981', 'Indestructible Dog Toy', '15.99', '162');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('982', 'Apple Pie Filling', '3.49', '131');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('983', 'Wrap Front Midi Skirt', '44.99', '99');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('984', 'High-Quality Yoga Mat', '34.99', '100');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('985', 'Cordless Electric Screwdriver', '39.99', '91');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('986', 'Portable Bluetooth Keyboard', '39.99', '149');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('987', 'Fleece Throw Blanket', '29.99', '47');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('988', 'Granola', '4.79', '101');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('989', 'Electric Kettle with Temperature Control', '49.99', '42');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('990', 'Beef Stew Meat', '5.99', '64');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('991', 'Cheese Stuffed Jalapenos', '5.99', '65');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('992', 'Multi-Layer Food Steamer', '39.99', '125');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('993', 'Mediterranean Olives', '6.49', '162');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('994', 'Magnetic Phone Case', '19.99', '74');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('995', 'Cinnamon Rolls', '4.49', '81');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('996', 'Smart WiFi Plug', '19.99', '100');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('997', 'Ethical Wool Scarf', '29.99', '101');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('998', 'Herbed Mushroom Risotto', '5.49', '121');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('999', 'Pretzel Bites', '4.99', '125');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('1000', 'Workstation Laptop Stand', '49.99', '116');