USE `autobasedb`;

INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('1', 'Avocado Oil', '8.49', '63');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('2', 'Pet Water Bottle', '18.99', '124');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('3', 'Stuffed Peppers with Quinoa', '7.99', '68');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('4', 'Classic Black Trousers', '54.99', '45');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('5', 'Spinach and Cheese Stuffed Shells', '5.99', '107');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('6', 'Crew Neck Sweater', '39.99', '96');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('7', 'Basil Pesto Pasta', '6.49', '58');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('8', 'Spicy Chicken Wings', '9.99', '103');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('9', 'Sour Cream', '3.49', '116');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('10', 'Shoe Organizer', '39.99', '88');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('11', 'Electric Griddle with Removable Plates', '59.99', '75');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('12', 'Car Diagnostic Scanner', '49.99', '119');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('13', 'Brussels Sprouts', '3.49', '130');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('14', 'Smartphone Tripod', '29.99', '112');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('15', 'Safety Pin Dispenser', '5.99', '145');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('16', 'Frozen Berry Medley', '5.49', '78');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('17', 'Frozen Mixed Vegetables', '1.99', '106');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('18', 'Savory Italian Herbs', '2.99', '142');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('19', 'Customizable Photo Calendar', '19.99', '143');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('20', 'Dark Chocolate Covered Almonds', '7.19', '131');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('21', 'Weighted Jump Rope with Counter', '14.99', '142');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('22', 'Adjustable Kitchen Broom Stand', '14.99', '83');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('23', 'Trainers with Mesh Inserts', '69.99', '78');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('24', 'Infrared Space Heater', '99.99', '130');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('25', 'LED Table Lamp', '29.99', '76');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('26', 'Sliced Cucumbers', '1.29', '157');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('27', 'Colorful Post-It Notes Set', '9.99', '122');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('28', 'Over-the-Door Hooks', '12.99', '79');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('29', 'Adjustable Laptop Desk', '59.99', '88');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('30', 'Pistachio Ice Cream', '4.99', '142');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('31', 'Self-Massaging Pillow', '49.99', '104');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('32', 'Organic Coconut Water', '2.79', '142');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('33', 'Vegetarian Sausage Links', '5.89', '130');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('34', 'Tattoo Kit', '99.99', '83');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('35', 'Electronic Drum Kit', '359.99', '138');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('36', 'LED Desk Lamp with USB Charging', '39.99', '106');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('37', 'Almond Joy Bars', '1.29', '66');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('38', 'Pineapple Teriyaki Chicken Mix', '6.99', '94');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('39', 'Pasta Sauce Mix', '1.29', '100');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('40', 'Crispy Tofu Bites', '4.99', '110');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('41', 'Chic Ankle Strap Heels', '69.99', '70');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('42', 'Cinnamon Roll Protein Bar', '2.99', '100');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('43', 'Non-Toxic Concrete Sealer', '39.99', '67');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('44', 'Basketball', '29.99', '60');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('45', 'Chocolate Coconut Granola', '3.79', '53');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('46', 'Cabbage', '1.29', '161');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('47', 'Outdoor Adventure Kit', '89.99', '65');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('48', 'White Rice', '1.49', '117');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('49', 'Artisan Pickles', '2.49', '118');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('50', 'Window Blinds', '59.99', '56');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('51', 'Wireless Car Charger', '24.99', '100');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('52', 'Digital Kitchen Timer', '14.99', '133');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('53', 'Chickpea Flour', '3.29', '151');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('54', 'Balsamic Vinegar', '4.99', '79');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('55', 'Portable Speakers', '69.99', '93');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('56', 'Salt and Pepper Grinder Set', '19.99', '116');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('57', 'Digital Photo Frame', '79.99', '56');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('58', 'Classic Vanilla Fudge', '4.49', '130');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('59', 'Compact Digital Camera', '249.99', '74');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('60', 'Vintage Graphic Tee', '25.99', '120');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('61', 'Electric Kettle', '39.99', '87');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('62', 'Training Soccer Ball', '19.99', '92');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('63', 'Puff Pastry', '5.49', '118');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('64', 'Adjustable Dog Harness', '24.99', '48');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('65', 'Pepper Jack Cheese Sticks', '2.49', '134');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('66', 'Compact Umbrella', '12.99', '73');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('67', 'Cacao Nibs', '6.49', '94');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('68', 'Cranberry Lime Sparkling Water', '1.5', '109');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('69', 'Deluxe First Aid Kit', '39.99', '89');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('70', 'Coffee Making Kit', '44.99', '142');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('71', 'Baking Powder', '1.79', '81');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('72', 'Bamboo Cutting Board', '22', '61');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('73', 'Smart LED Light Strip', '29.99', '79');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('74', 'Sporty Leggings', '39.99', '137');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('75', 'Pork Tenderloin', '10.99', '145');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('76', 'Adjustable Standing Desk', '299.99', '138');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('77', 'Water Bottle', '18.99', '137');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('78', 'Chocolate Mint Cookies', '2.29', '147');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('79', 'Vegetarian Chili', '3.99', '106');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('80', 'Mango Sticky Rice Dessert', '4.5', '121');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('81', 'Magnetic Spice Jars', '24.99', '130');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('82', 'Streaming Device', '49.99', '111');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('83', 'Grilled Vegetable Medley', '4.49', '85');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('84', 'Denim Jacket', '69.99', '95');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('85', 'Wall-Mounted Bookshelf', '39.99', '119');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('86', 'Honey Ginger Tea', '2.99', '110');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('87', 'Peach Fruit Cups', '1.99', '122');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('88', 'Oatmeal Raisin Cookies', '3.49', '91');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('89', 'Reusable Silicone Food Storage Bags', '19.99', '84');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('90', 'Computer Monitor Stand', '29.99', '94');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('91', 'Cranberry Citrus Sauce', '3.99', '52');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('92', 'Electric Ice Cream Maker', '59.99', '79');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('93', 'Portable Solar Path Lights', '39.99', '142');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('94', 'Pecan Pie Filling', '3.99', '96');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('95', 'Zesty Cilantro Lime Dressing', '3.29', '120');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('96', 'Truffle Parmesan Fries', '4.99', '124');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('97', 'Watercolor Set', '19.99', '60');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('98', 'Savory Oatmeal', '2.49', '109');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('99', 'Mushrooms', '2.99', '98');
INSERT INTO `Part` (ID, Name, Price, Stock) VALUES ('100', 'Chili Lime Corn Chips', '2.79', '130');